name: alpha
description: Human Resources employee self service
version: 1.10.3+121
analyzer:
  enable-experiment:
    - non-nullable
environment:
  # sdk: ">=2.12.0 <4.0.0"
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  fluttertoast: ^8.2.8
  http: ^1.2.2
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  badges: ^3.1.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  open_file: ^3.5.9
  rounded_loading_button_plus: ^3.0.1
  # url_launcher: ^6.3.1
  bubble: ^1.2.1
  clipboard: ^0.1.3
  animations: ^2.0.11
  # launch_review: ^3.0.1
  scroll_to_index: ^3.0.1
  # Remove: url_launcher: ^6.0.0

  expansion_tile_card: ^3.0.0
  flutter_spinkit: ^5.2.1
  # custom_switch: ^0.0.1
  easy_localization: ^3.0.7
  # detect_fake_location: ^2.0.0
  device_info_plus: ^11.1.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  # admob_flutter: ^2.0.0
  # geolocator: ^8.2.1
  line_icons: ^2.0.3
  flutter_linkify: ^6.0.0
  # expansion_card: ^0.1.0
  modal_bottom_sheet: ^3.0.0
  google_maps_flutter: ^2.9.0
  location: ^7.0.1
  shared_preferences_android: ^2.3.3
  shared_preferences_ios: ^2.1.1
  # advertising_id: ^2.3.0
  # geolocator: ^8.2.0
  # geocoding: ^2.0.4
  flutter_plugin_android_lifecycle: ^2.0.23
  url_launcher: ^6.3.1
  flutter_local_notifications: ^17.2.4
  sqflite: ^2.4.0

  flutter_localizations: # Add this line
    sdk: flutter         # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: TheSans
      fonts:
        - asset: fonts/Cairo-Regular.ttf